global using u32 = System.UInt32;
global using u64 = System.UInt64;
global using u16 = System.UInt16;
global using u8 = System.Byte;
global using s8 = System.SByte;
global using s16 = System.Int16;
global using s32 = System.Int32;
global using PHAL_DATA_TYPE = WiFiDriver.App.Rtl8812au.hal_com_data;
global using HAL_DATA_TYPE = WiFiDriver.App.Rtl8812au.hal_com_data;
global using PADAPTER = WiFiDriver.App.Rtl8812au._adapter;
global using BOOLEAN = System.Boolean;
global using static WiFiDriver.App.Rtl8812au.Logging;
global using static WiFiDriver.App.Rtl8812au.RTW_USB_SPEED;
global using static WiFiDriver.App.Rtl8812au.libusb_speed;
global using static WiFiDriver.App.Rtl8812au.Bits;
global using static WiFiDriver.App.Rtl8812au.RTL871X_HCI_TYPE;
global using static WiFiDriver.App.Rtl8812au.StatusConsts;
global using static WiFiDriver.App.Rtl8812au.rtw_xmit_consts;
global using static WiFiDriver.App.Rtl8812au.drv_types;
global using static WiFiDriver.App.Rtl8812au.hal_com_data_defs;
global using static WiFiDriver.App.Rtl8812au.usb_ops;
global using static WiFiDriver.App.Rtl8812au.hal_data;
global using static WiFiDriver.App.Rtl8812au.rtw_io;
global using static WiFiDriver.App.Rtl8812au.CommonConsts;
global using static WiFiDriver.App.Rtl8812au.hal_intf;
global using static WiFiDriver.App.Rtl8812au.odm_board_type;
global using static WiFiDriver.App.Rtl8812au.rtw_pwrctrl;
global using static WiFiDriver.App.Rtl8812au.os_intfs;
global using static WiFiDriver.App.Rtl8812au.usb_intf;
global using static WiFiDriver.App.Rtl8812au.halhwimg8812a_mac;
global using static WiFiDriver.App.Rtl8812au.phydm_regconfig8812a;
global using static WiFiDriver.App.Rtl8812au.phydm_interface;
global using static WiFiDriver.App.Rtl8812au.halhwimg8812a_bb;
global using static WiFiDriver.App.Rtl8812au.rtl8812a_dm;
global using static WiFiDriver.App.Rtl8812au.HalVerDef;
global using static WiFiDriver.App.Rtl8812au.phydm;
global using static WiFiDriver.App.Rtl8812au.rtw_odm;
global using static WiFiDriver.App.Rtl8812au.rtw_cmd;
global using static WiFiDriver.App.Rtl8812au.rtw_mlme_ext;
global using static WiFiDriver.App.Rtl8812au.rtl8812a_hal_init;
global using static WiFiDriver.App.Rtl8812au.rtw_wlan_util;
global using static WiFiDriver.App.Rtl8812au.hal_com;
global using static WiFiDriver.App.Rtl8812au.RcrBits;
global using static WiFiDriver.App.Rtl8812au.rtw_rf;
global using static WiFiDriver.App.Rtl8812au.rtl8812a_phycfg;
global using static WiFiDriver.App.Rtl8812au.UsbHalInit;
global using static WiFiDriver.App.Rtl8812au.rtw_efuse;
global using static WiFiDriver.App.Rtl8812au.phydm_hwconfig;
global using static WiFiDriver.App.Rtl8812au.halhwimg8812a_rf;
global using static WiFiDriver.App.Rtl8812au.rtw_ieee80211;
global using static WiFiDriver.App.Rtl8812au.hal_com_phycfg;
