global using u32 = System.UInt32;
global using u16 = System.UInt16;
global using u8 = System.Byte;
global using s32 = System.Int32;
global using static WiFiDriver.App.Rtl8812au.Logging;
global using static WiFiDriver.App.Rtl8812au.RTW_USB_SPEED;
global using static WiFiDriver.App.Rtl8812au.libusb_speed;
global using static WiFiDriver.App.Rtl8812au.Bits;
global using static WiFiDriver.App.Rtl8812au.RTL871X_HCI_TYPE;
global using static WiFiDriver.App.Rtl8812au.StatusConsts;
global using static WiFiDriver.App.Rtl8812au.rtw_xmit_consts;