global using u32 = System.UInt32;
global using u16 = System.UInt16;
global using u8 = System.Byte;
global using s32 = System.Int32;
global using PHAL_DATA_TYPE = WiFiDriver.App.Rtl8812au.hal_com_data;
global using HAL_DATA_TYPE = WiFiDriver.App.Rtl8812au.hal_com_data;
global using PADAPTER = WiFiDriver.App.Rtl8812au._adapter;
global using BOOLEAN = System.Boolean;
global using static WiFiDriver.App.Rtl8812au.Logging;
global using static WiFiDriver.App.Rtl8812au.RTW_USB_SPEED;
global using static WiFiDriver.App.Rtl8812au.libusb_speed;
global using static WiFiDriver.App.Rtl8812au.Bits;
global using static WiFiDriver.App.Rtl8812au.RTL871X_HCI_TYPE;
global using static WiFiDriver.App.Rtl8812au.StatusConsts;
global using static WiFiDriver.App.Rtl8812au.rtw_xmit_consts;
global using static WiFiDriver.App.Rtl8812au.drv_types;
global using static WiFiDriver.App.Rtl8812au.hal_com_data_defs;
global using static WiFiDriver.App.Rtl8812au.usb_ops;
global using static WiFiDriver.App.Rtl8812au.hal_data;
global using static WiFiDriver.App.Rtl8812au.rtw_io;
global using static WiFiDriver.App.Rtl8812au.Registers;
global using static WiFiDriver.App.Rtl8812au.hal_intf;