namespace Rtl8812auNet.Rtl8812au;

public enum EFUSE_DEF_TYPE
{
    TYPE_EFUSE_MAX_SECTION = 0,
    TYPE_EFUSE_REAL_CONTENT_LEN = 1,
    TYPE_AVAILABLE_EFUSE_BYTES_BANK = 2,
    TYPE_AVAILABLE_EFUSE_BYTES_TOTAL = 3,
    TYPE_EFUSE_MAP_LEN = 4,
    TYPE_EFUSE_PROTECT_BYTES_BANK = 5,
    TYPE_EFUSE_CONTENT_LEN_BANK = 6,
};